name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./weather  # Adjust to your Dockerfile location
        file: ./weather/dockerfile
        push: true
        tags: your_dockerhub_username/your_image_name:${{ github.sha }}  # Use SHA for unique tagging

    - name: Update Kubernetes Deployment
      run: |
        sed -i 's|image: your_dockerhub_username/your_image_name:.*|image: your_dockerhub_username/your_image_name:${{ github.sha }}|' kubernetes/deployment.yaml
        kubectl apply -f kubernetes/deployment.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}  # Set up your Kubeconfig secret

