name: Handle Repository Dispatch

on:
  repository_dispatch:
    types: [dockerhub-push]

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo snap install yq  # Install yq if not already installed

      - name: Update Kubernetes Deployment
        run: |
          TAG="${{ github.event.client_payload.tag }}"
          NEW_IMAGE="eliseror/new_repo:${TAG}"
          yq eval -i '.spec.template.spec.containers[0].image = "'$NEW_IMAGE'"' kubernetes/deployment.yaml
          echo "Updated image name to: $NEW_IMAGE"

